server:
  port: 8888

spring:
  application:
    name: config-service
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///${user.home}\OneDrive\바탕 화면\JEI\native-file-repo
        git:
          uri: https://github.com/Song-EunJu/spring-cloud-config
